### ISSUE TITLE
U+11F34 KAWI VOWEL SIGN AA should not become U+11F35 KAWI VOWEL SIGN ALTERNATE AA

### ISSUE THREAD

**Issue by dscorbett** [notofonts/kawi#14]
### Font
NotoSansKawi-Regular.otf

### Where the font came from, and when
Site: https://github.com/notofonts/kawi/releases/tag/NotoSansKawi-v1.000
Date: 2023-06-29

### Font version
Version 1.000

### Issue
After U+11F26 and U+11F2D, U+11F34 KAWI VOWEL SIGN AA is transformed into U+11F35 KAWI VOWEL SIGN ALTERNATE AA. The two forms were disunified because the choice of glyph is significant but not completely predictable. The font should not be overriding the form specified in the underlying text.

### Character data
𑼦𑼴𑼭𑼴
U+11F26 KAWI LETTER PA
U+11F34 KAWI VOWEL SIGN AA
U+11F2D KAWI LETTER LA
U+11F34 KAWI VOWEL SIGN AA

### Screenshot
![𑼦𑼴𑼭𑼴](https://github.com/notofonts/kawi/assets/1124347/63824bf7-848c-435b-9d3f-62b73fc5e7a8)

**Comment by simoncozens** [comment]
@holdontype I've commented out the `vowelAaAltForms` unless there was a good reason for it. I agree that if people want the ALTERNATE AA that's what they should encode. Let me know if you want to revisit.
