### ISSUE TITLE
Too low line height

### ISSUE THREAD

**Issue by Mercury13** [notofonts/kawi#6]
### Title 
Too low line height in Kawi, possibly OS/2 metrics

### Font
NotoSansKawi-Regular.ttf

### Where the font came from, and when
Site: beta branch of this repo
Date: 2023-04-07

### Font Version
1.000

### OS name and version
Windows 10 22H2

### Application name and version
Qt 6.1.3, LOo 7.3.2.2

### Issue
1. Write something tall (e.g. 11F07)
2. Clipped
3. Should not clip
4. Possibly OS/2 metrics are to blame. Other fonts (e.g. KawiMastuti used in my Unicodia) use these metrics: general asc/desc 1638/410, OS/2 asc/desc 2118/1556 — more than 1.5× taller. You use 800/200 for both pairs.

### Character data
All tall characters of Kawi, e.g.
U+11F02 Kawi sign Repha
U+11F06 Kawi letter I
U+11F07 Kawi letter Ii
U+11F08 Kawi letter U
U+11F09 Kawi letter Uu
U+11F0A Kawi letter Vocalic R
U+11F0B Kawi letter Vocalic Rr
U+11F0C Kawi letter Vocalic L
U+11F0D Kawi letter Vocalic Ll
U+11F0E Kawi letter E
U+11F0F Kawi letter Ai
U+11F10 Kawi letter O
U+11F33 Kawi letter Jnya
U+11F35 Kawi vowel sign Alternate Aa
U+11F36 Kawi vowel sign I
U+11F37 Kawi vowel sign Ii
U+11F38 Kawi vowel sign U
U+11F39 Kawi vowel sign Uu
U+11F3A Kawi vowel sign Vocalic R
U+11F3F Kawi vowel sign Ai
U+11F40 Kawi vowel sign Eu
U+11F41 Kawi sign Killer
U+11F42 Kawi conjoiner
U+11F43 Kawi danda
U+11F44 Kawi double danda
U+11F45 Kawi punctuation Section marker
U+11F46 Kawi punctuation Alternate section marker
U+11F52 Kawi digit Two
U+11F53 Kawi digit Three
U+11F55 Kawi digit Five
U+11F57 Kawi digit Seven
U+11F58 Kawi digit Eight
U+11F59 Kawi digit Nine

### Screenshot
LibreOffice.org
![image](https://user-images.githubusercontent.com/10164882/230667246-2481cea5-0b05-4cc7-beb3-e6ca2c306acc.png)

My Unicodia written in Qt 6.1.3
![image](https://user-images.githubusercontent.com/10164882/230667281-50e7f647-d2cf-4e50-bb9c-f56714da9809.png)

**Comment by holdontype** [comment]
<img width="394" alt="Screenshot 2023-04-15 at 10 49 54" src="https://user-images.githubusercontent.com/122390929/232181473-76aa15ed-f459-423f-8bf8-8862c9c2b58d.png">

Clipping is now fixed, screenshot provided using Libre Office 7.5.2.2 (ARCH64). Please do check on the newest gh-page export.

**Comment by Mercury13** [comment]
At last!
![image](https://user-images.githubusercontent.com/10164882/232246357-112f61d4-49db-4328-9540-5e0449f9ba38.png)

Taking it to my Unicodia. This is 1×!
![image](https://user-images.githubusercontent.com/10164882/232246375-da5dc995-7ac7-49f2-aae4-b1727b6902bb.png)

Should I close the issue?

**Comment by Mercury13** [comment]
Normal asc/desc are 800/200, and OS/2 asc/desc are 1250/960. When I set this font, the line becomes almost 2× taller. As this is the way Windows typography engine behaves — should I close?
